### ISSUE TITLE
Solution C is built on wrong assumptions

### ISSUE THREAD

**Issue by mnapoli** [mnapoli/bref-bootstrap-benchmarks#12]
I thought that the duration of a lambda was the time spend between these events:

- the lambda asks for an event to process (via the HTTP runtime API)
- the lambda sends a response for the event (via the API again)

From what I've seen in some tests the duration is actually between:

- the lambda asks for an event to process
- the lambda asks for **the next** event to process

It doesn't matter if we return a response early and keep processing things. It also doesn't matter if we pre-load stuff before a request comes in, because this is actually time spent in the previous lambda execution…

With that in mind, solution C doesn't actually save any time by booting Symfony *and then* waiting for an event.

I'm not sure though that C should be removed/marked as obsolete as I believe it can still be faster than B (there is not the overhead of passing the event via CLI parameters). However I think opcache is not enabled in C so current results are not up to date (I'll open a separate issue for that).

**Comment by mnapoli** [comment]
FYI I have asked clarification directly to AWS team members about that, I'll update here when I know more.

**Comment by bubba-h57** [comment]
Are you saying solution C does not save **billed** time? Or that it doesn't not save the actual **run** time?

_Sorry, been on vacation and got snowed in at the cabin with no internet. Just now getting caught back up._

**Comment by mnapoli** [comment]
Got confirmation by the AWS team, we are not saving billed time and we are not saving HTTP response time (or Lambda duration time).

So C doesn't seem like an interesting solution at all. It should be marked as obsolete in the README.

**Comment by bubba-h57** [comment]
Aren't we only booting Symfony on a cold start though? Or does the Lambda actually kill our `bootstrap` and then restart it for each request?

**Comment by mnapoli** [comment]
No worries ^^
