### ISSUE TITLE
Unable to Conenct to Socket

### ISSUE THREAD

**Issue by atrope** [mnapoli/bref-bootstrap-benchmarks#17]
Hi,
Sometimes when we make a request the requests fails with a 502.

The Log show us that 

```
Fatal error: Uncaught ErrorException: stream_socket_client(): unable to connect to unix:///tmp/php-fpm.sock (Connection refused) in /opt/vendor/hollodotme/fast-cgi-client/src/Socket.php:183
Stack trace:
#0 /opt/vendor/hollodotme/fast-cgi-client/src/Socket.php(191): hollodotme\FastCGI\Socket->handleFailedResource(111, 'Connection refu...')
#1 /opt/vendor/hollodotme/fast-cgi-client/src/Socket.php(162): hollodotme\FastCGI\Socket->connect()
#2 /opt/vendor/hollodotme/fast-cgi-client/src/Client.php(105): hollodotme\FastCGI\Socket->sendRequest(Object(class@anonymous))
#3 /opt/vendor/hollodotme/fast-cgi-client/src/Client.php(77): hollodotme\FastCGI\Client->sendAsyncRequest(Object(class@anonymous))
#4 /opt/bootstrap(161): hollodotme\FastCGI\Client->sendRequest(Object(class@anonymous))
#5 /opt/bootstrap(225): sendToApp('/v2/cd/32', Array, Object(hollodotme\FastCGI\Client))
#6 {main}

Next hollodotme\FastCGI\Exceptions\ConnectException: Unable to connect to FastCGI application: Connection refused in /opt/vendor/hollodotme/fast-cgi-c in /opt/vendor/hollodotme/fast-cgi-client/src/Socket.php on line 226
```

**This Happens in Solutions E and H**

I Will try to debug more and see if I can fix this problem

**Comment by barryvdh** [comment]
We currently check if the .sock file is present, before starting the loop that fetches the requests, but we don't check it for every request. Not sure why it happens though, perhaps the worker is restarted? Do you know if it comes back online? Otherwise we should always check the socket file and wait until it exists.

**Comment by barryvdh** [comment]
There is also a `--nodaemonize`, perhaps that's more reliable or makes it easy to check if the process is running. Or an option to restart after x requests (`pm.max_requests`) but I guess it's more random then that?

**Comment by mnapoli** [comment]
`--nodaemonize` sounds like a very good option, that way `bootstrap` will crash if php-fpm crashes, which would restart the lambda

**Comment by barryvdh** [comment]
@atrope How do you reproduce this? Is it only on AWS, or also locally? Not sure what AWS does when it goes to sleep or something.

**Comment by atrope** [comment]
Hi @barryvdh,
It was happening when the process would process something more than the default 5000ms then  UnixDomainSocket would timeout and never recover.

I Managed to fix that by  sending the request to the app withing aTry/Catch.. Something like this

```
  try {
          $response = makeResponse(sendToApp($uri, $event, $client));
        }
        catch (TimedoutException $e) {
          $headers = ["Status"=> ["504 Gateway Timeout"],"X-Powered-By"=> ["PHP/7.1.7"],"Content-Type"=> ["application/json"]];
          $response = ["multiValueHeaders" => $headers, "body" => json_encode(["message"=>"Timed Out"]), "statusCode" => 504];
        }
```

With that handling, the socket would timeout but would not exit and the requests would continue to serve.


Also, I increased UnixDomainSocket to 30s

`new Client(new UnixDomainSocket($socket,5000,$socketTimeout));`


Since I Changed it, I had no errors.

**Comment by barryvdh** [comment]
So like this? https://github.com/mnapoli/bref-bootstrap-benchmarks/issues/17

**Comment by atrope** [comment]
@barryvdh Yes this is great.
When you merge you can close here :+1: 
Just check out my Comment there.
