### ISSUE TITLE
Enable the Twig cache

### ISSUE THREAD

**Issue by mnapoli** [mnapoli/bref-bootstrap-benchmarks#2]
Currently the Twig cache is disabled in the Symfony test. This doesn't allow to compare with actual Symfony performances outside of AWS Lambda, this should be fixed.

**Comment by bubba-h57** [comment]
I enabled the Twig Cache in my tests. Assign this to me and I will sort it out for all the tests?

**Comment by mnapoli** [comment]
:+1: go ahead
