### ISSUE TITLE
Solution E

### ISSUE THREAD

**Issue by bubba-h57** [mnapoli/bref-bootstrap-benchmarks#6]
Solution E currently states that it would be _forwarding Lambda events to PHP-FPM via FastCGI._ I wrote a nodejs shim last summer that is similar. However, it simply forwards directly to `php-cgi` are you looking for something similar to this nodejs code or is Solution E really about trying to leverage PHP-FPM?

```node
/*jslint node: true */

const spawn = require("child_process").spawnSync;
const parser = require("http-string-parser");
var path = require("path");

exports.handler = function(event, context) {
    // Sets some sane defaults here so that this function doesn't fail
    // when it's not handling a HTTP request from API Gateway.
    var requestMethod = event.httpMethod || 'GET';
    var requestBody = event.body || '';
    var serverName = event.headers ? event.headers.Host : 'lambda_test.dev';
    var requestUri = event.path || '';
    var headers = {};
    var queryParams = '';

    // Convert all headers passed by API Gateway into the correct format for PHP CGI.
    // This means converting a header such as "X-Test" into "HTTP_X-TEST".
    if (event.headers) {
        Object.keys(event.headers).map(function (key) {
            headers['HTTP_' + key.toUpperCase().replace(/-/g, '_')] = event.headers[key];
            headers[key.toUpperCase().replace(/-/g, '_')] = event.headers[key];
        });
    }

    // Convert query parameters passed by API Gateway into the correct format for PHP CGI.
    if (event.queryStringParameters) {
        var parameters = Object.keys(event.queryStringParameters).map(function(key) {
            var obj = key + "=" + event.queryStringParameters[key];
            return obj;
        });
        queryParams = parameters.join("&");
    }

    // Spawn the PHP CGI process with a bunch of environment variables that describe the request.
    var scriptPath = path.resolve(__dirname + '/../../public/index.php')

    var php = spawn('php-cgi', ['-f', scriptPath], {
        env: Object.assign({
            REDIRECT_STATUS: 200,
            REQUEST_METHOD: requestMethod,
            SCRIPT_FILENAME: scriptPath,
            SCRIPT_NAME: '/index.php',
            PATH_INFO: '/',
            SERVER_NAME: serverName,
            SERVER_PROTOCOL: 'HTTP/1.1',
            REQUEST_URI: requestUri,
            QUERY_STRING: queryParams,
            AWS_LAMBDA: true,
            CONTENT_LENGTH: Buffer.byteLength(requestBody, 'utf-8')
        }, headers, process.env),
        input: requestBody
    });

    // When the process exists, we should have a compvare HTTP response to send back to API Gateway.
    var parsedResponse = parser.parseResponse(php.stdout.toString('utf-8'));

    // Signals the end of the Lambda function, and passes the provided object back to API Gateway.
    context.succeed({
        statusCode: parsedResponse.statusCode || 200,
        headers: parsedResponse.headers,
        body: parsedResponse.body
    });
};
```

**Comment by mnapoli** [comment]
Hi, this is interesting! I'm not sure about the performances of this (this is spawning a PHP process) but it would be definitely worth it to add it in the benchmark! Maybe this could be very useful to run PHP-style apps (Wordpress, etc.) which do not use PSR-7 or any kind of abstraction for HTTP requests/responses.

If you are able to send a pull request for a scenario H (or whatever the next letter is) that would be awesome!

**Comment by bubba-h57** [comment]
I will make it happen.

**Comment by bubba-h57** [comment]
We need `php-cgi` _(and also `php-fpm`) compiled into the `/opt/bin` directory of the PHP Layer for me to move forward. 

That is currently built over in [master/bin/php/build.sh](https://github.com/mnapoli/bref/blob/master/bin/php/build.sh) does it make sense to move the build script into this benchmark in order to mess around with it? I am very comfortable with making changes to it and providing a pull request, but it as we attempt a variety of things _(like if/when we attempt to create a **Lambda SAPI**)_ there is a potential for a fairly large quantity of changes to the build script.

What would you prefer me do?

**Comment by barryvdh** [comment]
I'll have a layer for you that adds it: `arn:aws:lambda:us-east-2:416360873395:layer:php-72:3`

I also have a PHP version that starts php-cgi in listening mode, not sure what is faster.

**Comment by barryvdh** [comment]
The only changes I did was settings disable-fpm and disable-cgi to enable it, and added `cp /tmp/bref/php-src-php-$PHP_VERSION/sapi/cgi/php-cgi /opt/bin/` below the one that copies php itself. I guess fpm is the same?

**Comment by barryvdh** [comment]
Basic attempt here: https://github.com/mnapoli/bref-bootstrap-benchmarks/pull/7
But using php and as a listener. But not really happy with it (yet)

**Comment by bubba-h57** [comment]
Nice! I will try your layer now with my Scenario H attempt :-)

**Comment by barryvdh** [comment]
This might be interesting though: https://twitter.com/symfony_en/status/1070611411762581504

Would take away some issues perhaps for the cgi implementation.

**Comment by mnapoli** [comment]
@barryvdh it seems this binary is running PHP-FPM though.

**Comment by mnapoli** [comment]
Right so I see no benefit to use that wrapper since we know the environment in which we run PHP. Additionally we are better off running PHP-FPM with one worker only, or even directly with php-cgi in FastCGI mode as discussed.

**Comment by mnapoli** [comment]
:+1:
